### ISSUE TITLE
number of pages

### ISSUE THREAD

**Issue by moe-men** [VinDazy/Quotes_Scrapping#1]
what if I want to scrap all the quotes ?

https://github.com/VinDazy/Quotes_Scrapping/blob/e1436ae7f6860aba598eeac6498e20a2d2dae3bf/main.py#L6

**Comment by Khallyll** [comment]
As of now, the website only supports 10 pages, with each page containing 10 quotes, resulting in a total of 100 quotes. 
 Thanks to your insight, I have made the necessary modifications to the code to ensure it works properly within the appropriate range and the changes will be committed very briefly, stay tuned.
